name: rgpv_direct
description: RGPV Direct.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase Database
  cloud_firestore: ^3.2.1
  firebase_core: ^1.19.1
  firebase_auth: ^3.4.1
  
  email_validator: ^2.0.1
  open_weather_widget: ^0.0.3
  flutter_inappwebview: ^5.4.3+7
  url_launcher: ^6.1.4
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.9
  google_mobile_ads: ^1.3.0
  flutter_launcher_icons: "^0.9.2"

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/app_logo/dot.-150x150.png
    - assets/images/2021-01-15.jpg
    - assets/images/567803-rgpv.jpg
    - assets/images/Rajiv_Gandhi_Proudyogiki_Vishwavidyalaya_(RGPV)_Admin_building_2.jpg
    - assets/images/rgvp.webp
    - assets/images/UIT-RGPV-Bhopal.jpg
    - assets/images/76438014.webp
    - assets/images/UIT_RGPV_Bhopal's_Main_Gate.jpg
    - assets/images/slide2.jpg
    - assets/app_logo/rgpv_direct_logo.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo/rgpv_direct_logo.png"